In [1]:
import numpy as np

In [13]:
arr = np.load("../dataset/SP500/baseline_data_sp500.npy", allow_pickle=True).item()

In [20]:
arr2 = np.load("../dataset/SP500/SP500.npy")

In [32]:
np.where(arr2 >= 0)[0].shape

(5986620,)

In [27]:
for i in range(arr2.shape[0]):
    print(arr2[i, 915])

[0.13653708 0.13713569 0.13633367 0.03608551 0.13700788]
[0.40426041 0.39552864 0.40436553 0.09072705 0.40175422]
[0.43928987 0.43503576 0.43233263 0.05139081 0.43785674]
[0.34475947 0.34166875 0.33852157 0.21122846 0.34070972]
[0.35412348 0.34696817 0.353408   0.27197955 0.35360504]
[0.86489667 0.85740037 0.85245373 0.09522104 0.85692839]
[0.60825153 0.62704919 0.60966144 0.03777192 0.62707367]
[0.46001825 0.45951861 0.45621545 0.146039   0.45448206]
[0.89797192 0.9053991  0.90855784 0.01184979 0.90950439]
[0.5752936  0.5764362  0.57212621 0.27934283 0.58220163]
[0.43280178 0.43521183 0.43312231 0.17559275 0.43542084]
[0.39406358 0.39122739 0.3893983  0.02289705 0.39239016]
[0.05846345 0.05874308 0.05968761 0.0952065  0.16644166]
[0.25196695 0.25147386 0.25102249 0.26201838 0.25341951]
[0.67992765 0.68248307 0.68205874 0.16902447 0.6915702 ]
[0.44888492 0.45024274 0.44717102 0.15926903 0.45052631]
[0.20687872 0.2068937  0.20802455 0.29715971 0.20709406]
[0.37027386 0.37037462 0.369473

In [16]:
i = 0
for k, v in arr.items():
    i += 1
    if k == "PEAK":
        print(i)

15


In [14]:

for k, v in arr.items():
    v.reset_index(drop=False, inplace=True)
    v.rename(columns={"index": "date"}, inplace=True)
    v.to_csv(f"../dataset/sp500-v2/{k}.csv", index=False)

In [23]:
v.shape

(2526, 7)

In [19]:
v.iloc[886]

date        2015-11-19 00:00:00
close                 61.862808
open                  61.655128
high                  62.234112
low                   61.567024
volume                6938527.0
adjclose              52.826824
Name: 886, dtype: object

In [7]:
a.to_csv("/raid/data/abner/for_ndq.csv", index=False)

In [10]:
a.iloc[1245]

date        2017-04-26 00:00:00
close                 35.919998
open                    36.1175
high                  36.150002
low                   35.845001
volume               80164800.0
adjclose              33.864464
Name: 1245, dtype: object